import Head from "next/head";

// ユーザー 一覧画面

export default function Home() {

  return (
    <div>
         <Head>
          <title>Daisuke Profile </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.png" />
        </Head>
  <main className=" bg-White px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        
   <section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-wrap w-full mb-20">
      <div class="lg:w-1/2 w-full mb-6 lg:mb-0">
        <h1 class="sm:text-3xl text-2xl font-bold title-font mb-2 text-white-900">Course Lists</h1>
        <div class="h-1 w-20 bg-indigo-500 rounded"></div>
      </div>
      {/* <p class="lg:w-1/2 w-full leading-relaxed text-gray-500">Whatever cardigan tote bag tumblr hexagon brooklyn asymmetrical gentrify, subway tile poke farm-to-table. Franzen you probably haven't heard of them man bun deep jianbing selfies heirloom prism food truck ugh squid celiac humblebrag.</p> */}
    </div>

    {/* 1列 */}
    <div class="flex flex-wrap -m-4">
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
         
          <h3 class="tracking-widest text-indigo-500 text-xs font-semibold title-font">Phase1</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4">まずはじめに</h2>
          <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
          {/* 6行以内に抑える */}
        </div>
      </div>
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
          
          <h3 class="tracking-widest text-indigo-500 text-xs font-semibold title-font">Phase1</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4">git基礎</h2>
          <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
        </div>
      </div>
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
       
          <h3 class="tracking-widest text-indigo-500 text-xs font-semibold title-font">Phase1</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4">ネットワークの<br></br>仕組み</h2>
          <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
        </div>
      </div>
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
         
          <h3 class="tracking-widest text-indigo-500 text-xs font-semibold title-font">Phase1</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4">Linux基礎</h2>
          <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
        </div>
      </div>
    </div>
     {/* 1列 */}
    
      {/* 1列 */}
      <div class="flex flex-wrap -m-4">
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
         
          <h3 class="tracking-widest text-indigo-500 text-xs font-semibold title-font">Phase1</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4">HTML/CSS</h2>
          <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
          {/* 6行以内に抑える */}
        </div>
      </div>
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
          
          <h3 class="tracking-widest text-indigo-500 text-xs font-semibold title-font">Phase2</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4">HTML/CSS</h2>
          <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
        </div>
      </div>
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
       
          <h3 class="tracking-widest text-indigo-500 text-xs font-semibold title-font">Phase2</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4">JavaScript基礎</h2>
          <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
        </div>
      </div>
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
         
          <h3 class="tracking-widest text-indigo-500 text-xs font-semibold title-font">Phase2</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4">PHP基礎</h2>
          <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
        </div>
      </div>
    </div>
     {/* 1列 */}
    

      {/* 1列 */}
      <div class="flex flex-wrap -m-4">
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
         
          <h3 class="tracking-widest text-indigo-500 text-xs font-semibold title-font">Phase2</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4">JavaScript応用</h2>
          <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
          {/* 6行以内に抑える */}
        </div>
      </div>
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
          
          <h3 class="tracking-widest text-indigo-500 text-xs font-semibold title-font">Phase2</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4">PHP応用</h2>
          <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
        </div>
      </div>
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
       
          <h3 class="tracking-widest text-indigo-500 text-xs font-semibold title-font">Phase2</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4">Docker基礎</h2>
          <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
        </div>
      </div>
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
         
          <h3 class="tracking-widest text-indigo-500 text-xs font-semibold title-font">Phase2</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4">MySQL基礎</h2>
          <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
        </div>
      </div>
    </div>
     {/* 1列 */}
    

      {/* 1列 */}
      <div class="flex flex-wrap -m-4">
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
         
          <h3 class="tracking-widest text-indigo-500 text-xs font-semibold title-font">Phase3</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4">Laravel<br></br>アプリ開発</h2>
          <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
          {/* 6行以内に抑える */}
        </div>
      </div>
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
          
          <h3 class="tracking-widest text-indigo-500 text-xs font-semibold title-font">Phase3</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4">Golangで<br></br>API開発</h2>
          <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
        </div>
      </div>
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
       
          <h3 class="tracking-widest text-indigo-500 text-xs font-semibold title-font">Phase3</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4">WordPressで<br></br>サイト制作</h2>
          <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
        </div>
      </div>
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
         
          <h3 class="tracking-widest text-indigo-500 text-xs font-semibold title-font">Phase3</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4">git応用</h2>
          <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
        </div>
      </div>
    </div>
     {/* 1列 */}
    

      {/* 1列 */}
      <div class="flex flex-wrap -m-4">
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
         
          <h3 class="tracking-widest text-indigo-500 text-xs font-semibold title-font">Phase4</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4">ポートフォリオ<br></br>制作</h2>
          <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
          {/* 6行以内に抑える */}
        </div>
      </div>
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
          
          <h3 class="tracking-widest text-indigo-500 text-xs font-semibold title-font">Phase4</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4">転職支援</h2>
          <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
        </div>
      </div>
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
       
          <h3 class="tracking-widest text-indigo-500 text-xs font-semibold title-font">Phase4</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4">初案件獲得<br></br>までの道</h2>
          <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
        </div>
      </div>
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
         
          <h3 class="tracking-widest text-indigo-500 text-xs font-semibold title-font">+@</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4">ディレクトリ構成</h2>
          <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
        </div>
      </div>
    </div>
     {/* 1列 */}
    

      {/* 1列 */}
      <div class="flex flex-wrap -m-4">
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
         
          <h3 class="tracking-widest text-indigo-500 text-xs font-semibold title-font">+@</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4">Vim基礎</h2>
          <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
          {/* 6行以内に抑える */}
        </div>
      </div>
      {/* <div class="xl:w-1/4 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
          
          <h3 class="tracking-widest text-indigo-500 text-xs font-semibold title-font">STEP2</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4">HTML/CSS</h2>
          <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
        </div>
      </div>
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
       
          <h3 class="tracking-widest text-indigo-500 text-xs font-semibold title-font">STEP3</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4">PHP</h2>
          <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
        </div>
      </div>
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
         
          <h3 class="tracking-widest text-indigo-500 text-xs font-semibold title-font">STEP4</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4">JavaScript</h2>
          <p class="leading-relaxed text-base">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
        </div>
      </div> */}

    </div>
     {/* 1列 */}
    
  </div>
</section>
   
      </main>
    </div>
  );
}