import Head from "next/head";
import { Header } from '../components/header';
import { Mv } from '../components/mv';
import { Service } from '../components/service';
import { Port } from '../components/port';
import { useState } from "react";

export default function Home() {

  // const [darkMode, setDarkMode] = useState(false);

  return (
    <div>
         <Head>
          <title>Daisuke Profile </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.png" />
        </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        
        <section className="min-h-screen">
        <Header />
        <Mv />
        </section> 
        <Service />
        <Port />
      </main>
    </div>
  );
}