import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillYoutube,
  AiFillGithub,
  AiOutlineFile,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
// 画像のインポート
import pr from "../public/pr.png";
import code from "../public/support-team.png";
import movie from "../public/movie.png";
import teach from "../public/teaching.png";
import Image from "next/image";
import web1 from "../public/h&y.png";
import web2 from "../public/unirage-creative.png";
import web3 from "../public/unirage.png";
import web4 from "../public/wabisabi.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">MyProfile</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center py-15">

            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden py-10 mt-20 md:h-96 md:w-96">
              <Image src={pr} layout="fill" objectFit="cover" />
            </div>
            
            <h2 className="text-5xl py-2 text-teal-600 font-bold dark:text-teal-400 md:text-6xl">
             Daisuke Yonekura
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
             WebEngineer and MovieCreater
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillTwitterCircle />
              <AiFillGithub />
              <AiFillYoutube />
              <AiOutlineFile/>
            </div>
           
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white font-bold">Services</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Web制作、動画制作、プログラミング講師を中心に現在個人事業主として活動中
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
               WebEngineer
              </h3>
              <p className="py-2">
               react/Nextjs/Laravel/WPを使って
               Web制作,アプリ制作,システム開発を行います。
              </p>
              <h4 className="py-4 text-teal-600">Tools</h4>
              <p className="text-gray-800 py-1">Javascript</p>
              <p className="text-gray-800 py-1">PHP</p>
              <p className="text-gray-800 py-1">React/Next.js</p>
              <p className="text-gray-800 py-1">Laravel</p>
              <p className="text-gray-800 py-1">WordPress</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={movie} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
               MovieCreater
              </h3>
              <p className="py-2">
               動画編集、動画制作を行います。YouTube等のSNSでバズる動画制作が得意です。
              </p>
              <h4 className="py-4 text-teal-600">Tools</h4>
              <p className="text-gray-800 py-1">AdobePremire</p>
              <p className="text-gray-800 py-1">AdobeAffterEfect</p>
              <p className="text-gray-800 py-1">Photoshop</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={teach} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Teacher</h3>
              <p className="py-2">
                PHP,Laravelをはじめてとしたプログラミング言語を教えております
              </p>
              <h4 className="py-4 text-teal-600">Im teaching</h4>
              <p className="text-gray-800 py-1">PHP</p>
              <p className="text-gray-800 py-1">Laravel</p>
              <p className="text-gray-800 py-1">ITパスポート</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white font-bold">Portofolio</h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                 className="rounded-lg object-cover w-fit"
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                 className="rounded-lg object-cover w-fit"
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
               className="rounded-lg object-cover w-fit"
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover w-fit"
                layout="responsive"
                src={web4}
              />
            </div>
            
           
          </div>
        </section>
      </main>
    </div>
  );
}
